export type ResultStatus = 'ready' | 'partial' | 'blocked' | 'not_applicable';
export type JobStatus =
  'queued' | 'running' | 'retry_wait' | 'succeeded' | 'failed' | 'cancelled' | 'expired';
export type Scope = { clusters: { cluster_id: string; namespaces: string[] | null }[] };
export type TimeRange = { start: string; end: string };
export type Asset = {
  id: string;
  name: string;
  cluster_id: string;
  model: string;
  gpus: number;
  utilization: number | null;
  memory: number | null;
  power: number | null;
  status: string;
  last_seen: string;
};
export type Pod = {
  id: string;
  name: string;
  namespace: string;
  cluster_id: string;
  node: string | null;
  gpu: string | null;
  kubernetes_phase: string;
  placement_status: string;
  relation_status: string;
  activity_status: string;
};
export type Job = {
  id: string;
  title: string;
  kind: 'rca' | 'report';
  status: JobStatus;
  stage: string;
  result_status: ResultStatus | null;
  narrative_status: string | null;
  created_at: string;
  started_at?: string;
  deadline_at: string;
  attempt_no: number;
  version: number;
  scope: Scope;
  time_range: TimeRange;
  target?: string;
  topic_ids?: string[];
  purpose_ids?: string[];
  parent_job_id?: string;
  incident_id?: string;
  can_cancel: boolean;
  can_retry: boolean;
  cancel_requested_at?: string;
  termination_reason?: string;
  request: Record<string, unknown>;
};
export type Incident = {
  id: string;
  label: string;
  title: string;
  node: string;
  cluster_id: string;
  severity: string;
  status: string;
  created_at: string;
  analysis_id: string;
  version: number;
  history: { at: string; status: string; reason: string; author: string }[];
};
export type Schedule = {
  id: string;
  name: string;
  frequency: string;
  local_time: string;
  weekday: number;
  day: number;
  timezone: string;
  enabled: boolean;
  revision: number;
  scope: Scope;
  topic_ids: string[];
  next_run: string;
  report_conditions?: Record<string, unknown>;
  reason?: string;
};
export type Knowledge = {
  id: string;
  title: string;
  kind: string;
  revision: number;
  status: string;
  content: string;
  compatibility: string;
  source: string;
  version: number;
  history?: { status: string; comment: string; author: string; at: string }[];
};
export type Model = {
  id: string;
  name: string;
  endpoint_url: string;
  model_name: string;
  artifact_revision: string;
  engine_revision: string;
  precision: string;
  enabled: boolean;
  version: number;
  secret_ref?: string;
};
export type Review = {
  id: string;
  subject_id: string;
  type: string;
  content: string;
  author: string;
  target: string;
  performed_at: string;
  supersedes_id?: string;
};
export type Message = {
  id: string;
  text: string;
  response: string;
  context: string;
  scope: Scope;
  created_at: string;
};
export type Database = {
  jobs: Job[];
  incidents: Incident[];
  schedules: Schedule[];
  knowledge: Knowledge[];
  models: Model[];
  routes: Record<string, string>;
  reviews: Review[];
  messages: Record<string, Message[]>;
};
